### ISSUE TITLE
Error when bow_flag is set

### ISSUE THREAD

**Issue by SaeedDarya** [DovelLabs/discover-document-clustering#3]
When run a command with bow_flag set, the script issues an error:

Traceback (most recent call last):
  File "app.py", line 143, in <module>
    results_df['BOW_Comparison_score'] = similarity_scores
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 2938, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3000, in _set_item
    value = self._sanitize_column(key, value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3636, in _sanitize_column
    value = sanitize_index(value, self.index, copy=False)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 611, in sanitize_index
    raise ValueError("Length of values does not match length of index")
ValueError: Length of values does not match length of index

**Comment by estringfellow** [comment]
Hi Saeed - What command did you use to run the script? "python app.py 10 1"?
Please let me know the exact command that you used so I can try to replicate the issue.
Thanks!

**Comment by SaeedDarya** [comment]
python app.py 10 1
